### ISSUE TITLE
Missing closing bracket

### ISSUE THREAD

**Issue by 0dayCTF** [LasCC/Hack-Tools#110]
https://github.com/LasCC/Hack-Tools/blob/939e12fb9bbd94f379a7457ca95e4559919c0295/src/components/web/PhpReverseShell.js#L35

**Comment by rb-x** [comment]
Hi @0dayCTF, thank you for reporting this,

We are planning to resolve some syntax issue in the v0.4 when we will have more time.
This was fixed in the branch  ( futur v0.4 ) [/features/http-utils/src/components/web/PhpReverseShell.tsx#L35](https://github.com/LasCC/Hack-Tools/blob/features/http-utils/src/components/web/PhpReverseShell.tsx#L35)

Please don't hesitate to contribute :+1: 

Best regards.
