### ISSUE TITLE
Removed from the Firefox Add-on site?

### ISSUE THREAD

**Issue by Tib3rius** [LasCC/Hack-Tools#111]
It looks like your amazing extension got removed from the Firefox Add-on site, did they tell you why?

https://addons.mozilla.org/en-US/firefox/addon/hacktools/

Is it possible to provide a compiled xpi so we can manually install in Firefox?

**Comment by LasCC** [comment]
Hello @Tib3rius,  

First of all, we would like to thank all Firefox users and especially you for your involvement in the extension.

The problem is known on our side for a few weeks with the Mozilla teams, there was a difference between the builds present in the release and the build sent.

We are doing our best to solve this problem as soon as possible.

Thanks again for the support, I'll keep you updated as soon as I have news from their side.

**Comment by rb-x** [comment]
After a long conversation and several mail and code reviews from Mozilla, the add-on was made available again on Firefox.
