### ISSUE TITLE
Windows Defender other AV reporting malware

### ISSUE THREAD

**Issue by eibrandr** [LasCC/Hack-Tools#115]
Hi there, 

This might be known -but not finding references to it. Windows defender is reporting the extension as containing malware, notably Win32/Uwamson.A!ml 

I suspect it's due to the content of the extension and that the AV heuristics are reporting on that, more than actual malware.

Just thought I'd let you know if you've not heard about it.

**Comment by rb-x** [comment]
Hello @eibrandr,

Indeed Microsoft Defender and other AV are mainly triggered because of  the php webshell, but it is a false positive.
All permissions related to the extension are defined  in the manifest and the chrome and mozilla team already reviewed in depth the source code.

Thank you for letting us know

**Comment by Drjacky** [comment]
> the chrome and mozilla team already reviewed in depth the source code.
So, why do they still report it?
<img width="624" alt="Screenshot 2023-03-12 at 21 58 06" src="https://user-images.githubusercontent.com/2296754/224576155-6fc8599d-6e11-4df2-9657-c3d86ff5ad64.png">
<img width="901" alt="Screenshot 2023-03-12 at 21 58 50" src="https://user-images.githubusercontent.com/2296754/224576205-c4a1ebff-118c-4c23-9916-55b99040013e.png">
