### ISSUE TITLE
source Build error - npm issue

### ISSUE THREAD

**Issue by noob0x01** [LasCC/Hack-Tools#140]
Hey Team any solution 

while Building from source code facing npm error issue. (npm latest version )

Second kindly add Custom Payload add features in the Next firefox (dist) version .

![image](https://github.com/LasCC/Hack-Tools/assets/51519007/213825d7-d468-4f9f-9dd1-93255007e7b2)

**Comment by rb-x** [comment]
Hey @noob0x01, thank you for the issue.

Firstly, which branch are you trying to build ?

If it's dev (even master btw), prefer one of those two package manager instead of npm : 

- yarn `npm install --global yarn` + `yarn && yarn build`
- pnpm (`npm install -g pnpm`) + `pnpm i && pnpm run build`

PS: If you want to avoid a headache, you can get the latest released version from GH or from Firefox/Chrome store directly.

Regarding the custom payload, we've thought of it before, and are currently working on it for the next release, especially the possibility to import your own methodology / payload in YAML you could take a look at it in (dev).
