### ISSUE TITLE
I got a question

### ISSUE THREAD

**Issue by KazukiDev** [LasCC/Hack-Tools#161]
Is this safe becuase it says virus when i downloaded it  and how would i onstall this and what can i sue it for

**Comment by rb-x** [comment]
Hello,
It is detected as malicious because the PHP reverse shell code snippet is recognized by Av's, it's completely safe and the code is open source + reviewed by mozilla and chrome extension dev teams.
If you want to use it without installing it in your on your browser, take a look at hacktools.sh, it's the webapp version.

**Comment by KazukiDev** [comment]
What can i do with this
