### ISSUE TITLE
am getting this issue about a backdoor can you pls explane 

### ISSUE THREAD

**Issue by chrismaher027** [LasCC/Hack-Tools#164]
Backdoor:AndroidOS/ZkarletFlash
AppData\Roaming\Mozilla\Firefox\Profiles\6fl59ag2.default-release-1730889483027\extensions\{f1423c11-a4e2-4709-a0f8-6d6a68c83d08}.xpi

Trojan:Script/Wacatac.B!ml
AppData\Roaming\Mozilla\Firefox\Profiles\6fl59ag2.default-release-1730889483027\extensions\{f1423c11-a4e2-4709-a0f8-6d6a68c83d08}.xpi

here is the SHA-256
96cfad19c851e4c3788ebe34eca7a268414c3cf642137133f30a6c3fcbccefe3 
can be checked on virustotal

**Comment by rb-x** [comment]
The extension is labeled as malicious due to its inclusion of tools like meterpreter, reverse shells, and web shells, even though it's a simple cheatsheet. If you're cautious about installing it, you can use the online version at hacktools.sh or clone the repository and serve it as a simple web app on your own.
